<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ApplicationIcon>chronsheet.ico</ApplicationIcon>
    <RootNamespace>Chronosheet</RootNamespace>
    <AssemblyName>Chronosheet</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
    <PackageReference Include="ClosedXML" Version="0.102.2" />
  </ItemGroup>

</Project>
